### ISSUE TITLE
Unwanted characters received after parsing

### ISSUE THREAD

**Issue by uNouss** [camfort/fortran-src#258]
Hi, I have this file:

```fortran
      PROGRAM MYPROG
         IF (I .LT. 2) THEN
            I = 3
         END IF
      END
```

When I parse it I get this result and there are two of these two characters `:|` that appear in the resulting AST.

<details>
<summary>Here the AST</summary>

```hs
ProgramFile {programFileMeta = MetaInfo {miVersion = Fortran77,
                                         miFilename = "./fortran77.f"},
             programFileProgramUnits = [PUMain ()
                                               (1:7)-(5:9)
                                               (Just "myprog")
                                               [BlIf ()
                                                     (2:10)-(4:15)
                                                     Nothing
                                                     Nothing
                                                     ((ExpBinary ()
                                                                 (2:14)-(2:21)
                                                                 LT
                                                                 (ExpValue ()
                                                                           (2:14)-(2:14)
                                                                           (ValVariable "i"))
                                                                 (ExpValue ()
                                                                           (2:21)-(2:21)
                                                                           (ValInteger "2"
                                                                                       Nothing)),
                                                       [BlStatement ()
                                                                    (3:13)-(3:17)
                                                                    Nothing
                                                                    (StExpressionAssign ()
                                                                                        (3:13)-(3:17)
                                                                                        (ExpValue ()
                                                                                                  (3:13)-(3:13)
                                                                                                  (ValVariable "i"))
                                                                                        (ExpValue ()
                                                                                                  (3:17)-(3:17)
                                                                                                  (ValInteger "3"
                                                                                                              Nothing)))]) :|
                                                      [])
                                                     Nothing
                                                     Nothing]
                                               Nothing]}

```

</details>

The command I used for compilation: `fortran-src -v77l file.f` and `fortran-src file.f`

#### EDIT

I don't know if those characters are there by design. 

As I understand it, this is the constructor of a non-empty list. 

But is it necessary for this to appear in the AST?

**Comment by uNouss** [comment]
Yes, I try to analyse the AST. 

In fact, it would be better to analyse the structure rather than the syntax of the AST, especially as the syntax can change faster than the structure itself (in my opinion). 

That's why I did this issue #215 to serialise the AST to XML or JSON. 

But the implementation that was done was less precise (in particular the lack of tree node types) than the one produced by the AST, so I stuck with the idea of parsing the AST.

But I added support for those characters, so it's fine. I thought it was a mistake. It shows that I don't know anything about Haskell, hence the misunderstanding.

**Comment by raehik** [comment]
> the implementation that was done was less precise (in particular the lack of tree node types) than the one produced by the AST

That's a shame -- I was hoping that the JSON representation wouldn't impact this. You still have typing, but where it's not required explicitly, constructors aren't printed. Let me give a quick example:

<details>
<summary>`cabal run -- fortran-src-extras serialize -v 90 -t yaml encode FILE`</summary>

```yaml
meta:
  miFilename: <stdin>
  miVersion: fortran90
program_units:
- anno: []
  blocks:
  - anno: []
    blocks: null
    conditions:
    - - anno: []
        left:
          anno: []
          span: (2:14)-(2:14)
          tag: value
          value:
            contents: i
            tag: variable
        op:
          tag: lt
        right:
          anno: []
          span: (2:21)-(2:21)
          tag: value
          value:
            contents:
            - '2'
            - null
            tag: integer
        span: (2:14)-(2:21)
        tag: binary
      - - anno: []
          label: null
          span: (3:13)-(3:17)
          statement:
            anno: []
            expression:
              anno: []
              span: (3:17)-(3:17)
              tag: value
              value:
                contents:
                - '3'
                - null
                tag: integer
            span: (3:13)-(3:17)
            tag: assign_expression
            target:
              anno: []
              span: (3:13)-(3:13)
              tag: value
              value:
                contents: i
                tag: variable
          tag: statement
    end_label: null
    label: null
    name: null
    span: (2:10)-(4:15)
    tag: if
  name: myprog
  span: (1:7)-(5:9)
  subprograms: null
  tag: main
```
</details>

Reformatting, we can see

```yaml
program_units:
- blocks:
  - tag: if
    conditions: [ ... ]
    blocks: null # else clause
    span: (2:10)-(4:15)
```

which corresponds to `BlIf`. The prefix is omitted because it's inherent: the object is an element in a list of blocks. I suppose it may mean more context in parsing, since you have to think about the structure of the parent element. I generally like this, since a "global" parser that just looks at `tag` every time to decide the element is very fragile.

Does this work for your use case? I'd be interested in making it work if not.
